baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ESuperstore'
theme = 'bs5theme'
enableGitInfo = true
sectionPagesMenu = "superstore"

[[menus.main]] 
  identifier = "HOME"
  name = "HOME"
  url = "/"
  weight = 100

[[menus.main]] 
  identifier = "SUPERSTORE"
  name = "SUPERSTORE"
  url = "/superstore"
  weight = 200

[[menus.main]] 
  identifier = "ABOUT"
  name = "ABOUT"
  url = "/about"
  weight = 300

[[menus.main]] 
  identifier = "CONTACT"
  name = "CONTACT"
  url = "/contact"
  weight = 400

[[menus.footer]]
  identifier = "About"
  name = "About"
  url = "/about"
  weight = 500

[[menus.footer]] 
  identifier = "Contact"
  name = "Contact"
  url = "/contact"
  weight = 600
