baseURL: 'https://example.org/'
languageCode: 'en-us'
title: 'SurgiMedShop'
enableGitInfo: true

module:
  mounts:
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"
    - source: "node_modules/bootstrap"
      target: "assets/scss/bootstrap"
    - source: "node_modules/@fortawesome/fontawesome-free"
      target: "static/fontawesome"
    - source: "node_modules"
      target: "static/js"

menus:
  main:
    - identifier: "Home"
      name: "Home"
      url: "/"
      weight: 100
    - identifier: "About"
      name: "About"
      url: "/about"
      weight: 110
    - indentifier: "Contact"
      name: "Contact"
      url: "/contact"
      weight: 120
    - identifier: "Shop"
      name: "Shop"
      url: "/shop"
      weight: 200
    - indentifier: "Delivery"
      name: "Delivery"
      url: "/delivery"
      weight: 300
    - indentifier: "Privacy"
      name: "Privacy"
      url: "/privacy"
      weight: 400

  footer:
     - identifier: "About"
       name: "About"
       url: "/about"
       weight: 500

