[build]
publish = "public"
functions = "netlify/functions/hello"
command = "npm i && node ./esmscript.prod.mjs && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
